
url: https://www.insightarchitectures.com
title: Insight Architectures
author: Renato Golia
description: 'Insight Architectures is a software architecture and development consultancy that delivers tailor-made software solutions and services to all kinds of businesses.'
copyright: 'Copyright &copy; 2022 Insight Architectures AB. All Rights Reserved.'

markdown: kramdown
# permalink: pretty

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - serve.sh

include:
  - _pages

settings:
  google-analytics-tracking-id: G-MFC8KNLDFJ

defaults:
  - scope:
      path: ""
    values:
      layout: default
      hero: true
