
url: https://www.insightarchitectures.com
title: Insight Architectures
email: info@insightarchitectures.com
author: Renato Golia
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2020 Insight Architectures AB. All Rights Reserved.'

markdown: kramdown
permalink: pretty

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - serve.sh

sass:
  style: compressed

social:
- title: twitter
  url: https://twitter.com/insightarchs
- title: github
  url: https://github.com/insight-architectures/
- title: linkedin
  url: https://www.linkedin.com/company/insight-architectures/