
url: https://www.insightarchitectures.com
title: Insight Architectures
author: Renato Golia
description: 'Insight Architectures is a software architecture and development consultancy that delivers tailor-made software solutions and services to all kinds of businesses.'
copyright: 'Copyright &copy; 2022 Insight Architectures AB. All Rights Reserved.'

markdown: kramdown
# permalink: pretty

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - serve.sh
  - README.md

include:
  - _pages

settings:
  google-analytics-tracking-id: G-MFC8KNLDFJ

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "customers"
    values:
      layout: customers

collections:
  projects:
    output: true
    permalink: "/:collection/:title"

page_gen-dirs: true

page_gen:
  - data: 'team'
    template: 'team'
    name: 'id'
    dir: 'team'
    filter: is_active
    # title_expr: "Our team: " + record['first_name'] + "_" + record['last_name']
    title_expr: record['first_name'] + " " + record['last_name']
  - data: 'customers'
    template: 'customer'
    name: 'id'
    dir: 'customers'
    title: name